![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [ ]:
my_array = np.arange(10)
print(my_array)

In [ ]:
print(my_array[::-2])

In [ ]:
print(my_array[my_array % 2 == 1][::-1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array)

In [ ]:
print(my_array[-2:-4:-1])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
print(my_array)

In [ ]:
print(my_array[2::-1])

In [ ]:
print(sorted(my_array[:3],reverse=True))

In [ ]:
np.take(my_array, [2,1,0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

In [ ]:
my_matrix.T

In [ ]:
print(my_matrix)

In [ ]:
print(my_matrix[::-1,::-1])

In [ ]:
print(np.flip(my_matrix))

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
print(my_matrix)

In [ ]:
print(my_matrix[:2,:2])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
print(my_matrix)

In [ ]:
print(my_matrix[::2,::2])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
print(my_matrix)

In [ ]:
print(my_matrix[:3,::-1])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [2]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [ ]:
x == "Loro"

In [ ]:
x[x == "Loro"]

In [ ]:
print(np.where(x == "Loro")[0])

In [4]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [3]:
np.where(x == "Loro", x, np.nan)

DTypePromotionError: The DType <class 'numpy.dtypes.StrDType'> could not be promoted by <class 'numpy.dtypes._PyFloatDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyFloatDType'>)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [ ]:
x = np.arange(20).reshape(2,5,2)
print(x)

In [ ]:
print(x.ndim)
print(x.shape)
print(x.size)

In [ ]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

In [ ]:
print(x.dtype)

In [ ]:
x = np.full(10, 0)
print(x)

In [ ]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

In [ ]:
print(x.dtype)

In [ ]:
x = np.full(10, 0, dtype=np.int8)
print(x)

In [ ]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

In [ ]:
2 ** 8

In [ ]:
# 101010110

In [ ]:
2**0 + 2**1 + 2**2 + 2**3 + 2**4 + 2**5 + 2**6 + 2**7

In [ ]:
[-128,127]

In [ ]:
x[3] = 1
# x[3] = 127
# x[3] = 128
print(x)

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
x = np.arange(10,50)
print(x)

In [ ]:
print(x[::-1])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [6]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)

[1 2 0 0 4 0]


In [7]:
type(np.where(ejer_12 != 0)[0])

numpy.ndarray

In [8]:
ejer_12[np.where(ejer_12 != 0)]

array([1, 2, 4])

In [10]:
def f_ejer_12(array_1d):
    return np.where(array_1d != 0)[0]

In [11]:
arr_ej = np.array([3,7,2,0,5,0])
print(f_ejer_12(arr_ej))
print(arr_ej[f_ejer_12(arr_ej)])

[0 1 2 4]
[3 7 2 5]


In [ ]:
np.nonzero(ejer_12)[0]

In [ ]:
np.argwhere(ejer_12)

In [ ]:
np.argwhere(ejer_12).reshape(len(np.argwhere(ejer_12)))

In [ ]:
np.hstack(np.argwhere(ejer_12))

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [13]:
x = np.random.randint(100, size=(10,10))
print(x)
print("Minimo", np.min(x), x.min())
print("Máximo", np.max(x), x.max())
print("Sumatorio", np.sum(x), x.sum())
print("Media", np.mean(x), x.mean())
print("Mediana", np.median(x))

[[90 97 74 76 51 70 16 40 29 98]
 [ 2 46 52  9 92 44 82 20 97 25]
 [ 1 11 27 36 93 61 28 26 48 19]
 [ 7 93 57 32 98 48  3 50 53 94]
 [79 27 54 85 19 92 51 90 93 57]
 [84 64 75 62 96 89 16 36 92  4]
 [22 67 68  2 42 34 97 22 30 49]
 [75 57 62  1 64 51  3 17 33 64]
 [11 67 35 97  4 50 38 22 80 63]
 [ 7 37 13 88 60 76 55 94 40 47]]
Minimo 1 1
Máximo 98 98
Sumatorio 5104 5104
Media 51.04 51.04
Mediana 51.0


In [ ]:
# ej = np.array([1000, 1000, 1100, 1100, 9000])
# print(ej.mean())
# print(np.median(ej))

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [18]:
x = np.random.random(30)
print(x)
print(x.mean())

[0.06736947 0.34774856 0.31966453 0.90478709 0.6489806  0.88070273
 0.42820903 0.78571528 0.64763572 0.14420113 0.046366   0.33139044
 0.81634958 0.66807702 0.74380917 0.1986238  0.30961513 0.48878512
 0.07201025 0.64312004 0.09231035 0.11857945 0.36383381 0.04364448
 0.56258767 0.26617106 0.58179012 0.73450925 0.42088151 0.95338244]
0.4543616941495073


In [ ]:
print(x.sum()/len(x))

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [19]:
ejer_15 = np.full((10,10), 1)
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [20]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
def f_ejer_15(tamaño):
    matrix = np.full(tamaño, 1)
    matrix[1:-1, 1:-1] = 0
    return matrix

In [22]:
print(f_ejer_15((3,3)))

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [28]:
print(f_ejer_15((8,8)))

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [24]:
print(f_ejer_15((2,2)))

[[1 1]
 [1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [49]:
x = np.zeros((8,8), dtype=np.int16)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [50]:
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [51]:
a = np.array([[0,1],
              [1,0]])
print(a)

[[0 1]
 [1 0]]


In [52]:
x = np.tile(a, (3,3))
print(x)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [53]:
x = np.random.randint(1,20, (5,5))
print(x)

[[16  6  4 19  4]
 [ 1 16 14 14  9]
 [ 6  7 19  8  2]
 [16  9 11  3  6]
 [19 15 12  3  9]]


In [54]:
np.mean(x)

np.float64(9.92)

In [55]:
(x - np.mean(x)) / np.std(x) 

array([[ 1.08032609, -0.69652603, -1.05189646,  1.61338173, -1.05189646],
       [-1.5849521 ,  1.08032609,  0.72495567,  0.72495567, -0.1634704 ],
       [-0.69652603, -0.51884082,  1.61338173, -0.34115561, -1.40726688],
       [ 1.08032609, -0.1634704 ,  0.19190003, -1.22958167, -0.69652603],
       [ 1.61338173,  0.90264088,  0.36958524, -1.22958167, -0.1634704 ]])

In [56]:
np.mean((x - np.mean(x)) / np.std(x)) 

np.float64(-2.4424906541753444e-17)

In [57]:
np.std((x - np.mean(x)) / np.std(x)) 

np.float64(0.9999999999999999)

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [58]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [59]:
y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [62]:
z = x.copy()
z[(z >= 3) & (z <= 8)] *= -1
print(z)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [73]:
seq = np.arange(11)

array_19 = np.where((seq > 3) & (seq < 8), -1, seq)
print(array_19)
array_19 = np.where((seq > 3) & (seq < 8), -seq, seq)
print(array_19)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
