![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [ ]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
np.__version__

'2.4.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [21]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [19]:
matriz = np.full((4,3), True)
print(matriz)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [22]:
array_pares = my_array[::2]
print(array_pares)

[0 2 4 6 8]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [26]:
array_impar = my_array.copy()
array_impar[nuevo_array % 2 != 0] = -1
print(array_impar)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [32]:
array_new = my_array.copy()
array_new = np.where(array_new % 2 != 0, 10, array_new)
print(array_new)

[ 0 10  2 10  4 10  6 10  8 10]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [48]:
my_array2 = my_array.reshape(2, 5)
print(my_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [53]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate((a,b)))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [54]:
print(np.concatenate((a,b), axis = 1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [56]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [59]:
np.concatenate?

Signature:      
np.concatenate(
    arrays,
    /,
    axis=0,
    out=None,
    *,
    dtype=None,
    casting='same_kind',
)
Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versiona

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [67]:
my_array = np.arange(10)
print(my_array)
producto = my_array * 10
print(producto)
print(my_array[0])
print(my_array[-1])
print(my_array[1:8:])

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [69]:
my_matrix = [[1,2,3],
            [4,5,6],
            [7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [70]:
print(np.arange(1, 50, 3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [73]:
print(np.arange(4, 1, -0.25))

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [ ]:
from PIL import Image
import matplotlib.pyplot as plt

imagen = Image.open('./img/numpy.png')

# Convierte la imagen en un array numpy
array_imagen = np.array(imagen)
print(array_imagen.shape)

(306, 765, 4)


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [79]:
array_4 = np.arange(4)
print(array_4)

matriz = array_4.reshape((2,2))
print(matriz)

[0 1 2 3]
[[0 1]
 [2 3]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [94]:
print(np.random.randint(100, size = (3, 3, 5))*4)

[[[ 88  88 364  60 116]
  [284 104 292 332  52]
  [376 340 184 224  76]]

 [[152 340  12 168  44]
  [152 280  80 240 296]
  [ 56 232  20 392 292]]

 [[112 352 180  60 124]
  [280 256 304 172 308]
  [320 144 164 192 132]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [89]:
array_bool = np.array([True, False, True, True, False, False, True, False, True, False])
matriz_bool = array_bool.reshape((2,5))
print(matriz_bool)

[[ True False  True  True False]
 [False  True False  True False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [98]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)

print("Número de elementos:", x.size)
print("Dimensiones:", x.ndim)
print("Forma del array:", x.shape)

[[[11 14 16 11 12 19]
  [12 10 12 17 13 14]]

 [[17 16 10 17 16 11]
  [12 13 10 10 10 17]]

 [[14 15 10 17 16 14]
  [10 18 11 11 10 12]]

 [[10 19 16 18 18 14]
  [19 19 13 13 17 12]]

 [[14 14 17 10 17 17]
  [15 17 13 10 19 18]]]
Número de elementos: 60
Dimensiones: 3
Forma del array: (5, 2, 6)
